### ISSUE TITLE
[English Version Only] Can't view earnings ever since January 2020

### ISSUE THREAD

**Issue by Lunacie** [gaelgthomas/mentor-statistics-openclassrooms#10]
Ever since the 01/01/2020, it has became impossible to view my earnings for this month.
This is what the display looks like : 
<img width="889" alt="screenshot01" src="https://user-images.githubusercontent.com/12446225/72737745-76abd400-3ba0-11ea-98ee-e3517b9bec89.png">

It seems like the plugin is no longer able to retrieve the sessions for this month and is displaying {0} instead of the month. All the earnings are therefore changed to 0.
The same thing is happening with the other tables.

Is there a way that you can fix this without having to change the page language, please ? 
I never browse the OC website in french even though I am a french mentor as well as Intl.
Thank you in advance.

**Comment by gahfy** [comment]
@Lunacie I can't find the extension working in english version of OpenClassrooms (even in `language-selector` branch)
@gael-thomas Is there any published release which would be not up-to-date with repo (before I start working on making the extension fully working for english version of OpenClassrooms)?

**Comment by gahfy** [comment]
@Lunacie A Pull Request has been made to make the extension fully available in english. Everything will be fixed with that PR.

**Comment by gaelgthomas** [comment]
Hello @Lunacie,

I merged and created a release with the @gahfy updates.
Please refer to [this link to download the latest version](https://github.com/gael-thomas/Mentor-Statistics-OpenClassRooms/releases/tag/1.2) of the extension.

Thank you for waiting.
I close the issue.
