### ISSUE TITLE
[Bug] Rester longtemps sur la page d'historique charge les stats des années précédentes

### ISSUE THREAD

**Issue by gahfy** [gaelgthomas/mentor-statistics-openclassrooms#11]
Exemple, janvier 2020, j'ai fait 110 euros de chiffre, janvier 2019, j'avais fait 80 euros de chiffre, si je reste sur la page suffisamment longtemps, il va m'afficher 190 euros dans la colonne janvier.

Je vais faire une PR dans le week-end pour corriger ce bug

**Comment by Coubiac** [comment]
Même bug pour moi :)
