### ISSUE TITLE
Extension no longer works since OC's website update

### ISSUE THREAD

**Issue by XenoX** [gaelgthomas/mentor-statistics-openclassrooms#15]
Hello ! 

Everything is in the title 🤓

**Comment by gaelgthomas** [comment]
Hello @XenoX,

I fixed the extension problem, please refer to [the last release](https://github.com/gael-thomas/Mentor-Statistics-OpenClassRooms/releases/tag/1.2) to update your extension (1.2.1).

Unfortunately, OpenClassrooms added a captcha: the result is now slow to appear, and sometimes the result can be wrong. If it happens to you, please refresh your page. 

Thank you!
