### ISSUE TITLE
Amount for no-show not correct

### ISSUE THREAD

**Issue by Deyine** [gaelgthomas/mentor-statistics-openclassrooms#6]
Hello @gael-thomas , thanks for this great plugin. Really useful, I use it since the first day you posted it :-)

I just noticed today that sometimes, the amount for no-show is not correct as you can see in the screen capture. The number of no-show is correct (4 for level 3) , the total should be 80€ instead of 100€

<img width="602" alt="Screen Shot 2019-10-11 at 13 35 24" src="https://user-images.githubusercontent.com/193329/66656143-ed921200-ec2c-11e9-9814-1b1e08343ff4.png">

**Comment by gaelgthomas** [comment]
Hello @Deyine,

Thanks for your bug report!
I'm so happy to see that you use the extension since day one!

I will work on it once I have the time (exam period).

Have a nice day!

**Comment by gahfy** [comment]
Hello @Deyine,

Looks like this issue is due to "Étudiante absente" (for female students) which is not fixed in public extension, but fixed in this repo.

@gael-thomas Do you know when a new version will be released?

**Comment by gaelgthomas** [comment]
Hello @Deyine,

I merged and created a release with the @gahfy updates.
Please refer to [this link to download the latest version](https://github.com/gael-thomas/Mentor-Statistics-OpenClassRooms/releases/tag/1.2) of the extension.

Thank you for waiting.
I close the issue.
