### ISSUE TITLE
Name of months is not correct

### ISSUE THREAD

**Issue by gahfy** [gaelgthomas/mentor-statistics-openclassrooms#8]
The name of "Janvier" months is not displayed correctly, as "{0}" is displayed instead of "Janvier".

This issue will be fixed by #7

**Comment by gaelgthomas** [comment]
Hello @gahfy,

Thank you so much for your fix.
I merged it into the official repository.

I also added your name in contributors part of [Readme](https://github.com/gael-thomas/Mentor-Statistics-OpenClassRooms/blob/master/README.md).
